### ISSUE TITLE
install seems broken.

### ISSUE THREAD

**Issue by xguse** [kynikos/outspline#373]
I am continually getting this error no matter how I call `python setup.py ...`:

```python
Traceback (most recent call last):
  File "setup.py", line 23, in <module>
    import config
ImportError: No module named config
```

I have tried using the AUR but i keep getting a message that it cant be found on the AUR.

No matter I clone the AUR repo from the website (so it IS on AUR -- dunno what my system's issue is with not finding it).  Running `makepkg -si` I get the same message WHEN I am able to download it from sourceforge.  Why are you pointing SF in the `PKGBUILD` when it is hosted here at github, btw?

I always get the config module error.  Have you renamed things lately?  Also your use of `import config` rather than `from config import Config` confused me but maybe its just a style thing I am not used to seeing.

In anycase I can not get it to install.

Ideas?

**Comment by xguse** [comment]
Ok I am pretty sure I know what was happening.

Because I couldnt get it from the AUR I pulled it from Github.  That is a mistake that you dont really warning people about.  At least not in the README for this repo which would be a good place.  I figured this out by tracing tracebacks to the symlinks that you use deep inside.

I have since searched for this info intentionally in the wiki and it is indeed sort of there but under the dev section and I dont think I found a warning to folks who might expect (and why wouldn;t they) to be able to clone and build the repo.

Why not include the external links as submodules?  At least then when I tried to pull any submodules down (thinking I must be missing something) I would have corrected my issues.

Anyway, as a warning to others: just cURL it from the SourceForge site (as annoying on principal that is for a repo hosted on github).

**Comment by kynikos** [comment]
Hey Gus, first of all thank you for reporting your problems and even your workarounds :)

Did you initially try to follow [the wiki](https://github.com/kynikos/outspline/wiki/Installation-in-Arch-Linux) to install from the AUR? Because I forgot to update the curl urls after the AUR recently migrated to version 4, so curl was actually downloading a 404 HTML page with a tar.gz extension, and trying to extract it would have obviously failed. Is that what you mean with "Because I couldnt get it from the AUR [...]"? That may have triggered all your subsequent attempts to find alternative installation methods. If that's the case, fixing the wiki (already done) should prevent the problem from happening to others; I've tried to reinstall following that procedure and now it works for me, please confirm it works for you as well, since installing from the AUR (or manually from SourceForge) is the only currently supported method, see [Getting started](https://github.com/kynikos/outspline/wiki/Getting-started).

Anyhow, if I understand correctly, after failing to download the snapshot with curl because of the wiki issue, you tried to clone the GitHub repo, but you weren't aware that the files on GitHub, AUR and SourceForge all have different purposes:

* GitHub contains the complete development environment: Outspline can be *run* (but *not installed*) from there by following [these instructions](https://github.com/kynikos/outspline/wiki/Development-environment); trying to *install* Outspline directly from there requires a more complicated release procedure, which is outlined in the `RELEASE` text file and not intended to be used by non-developers.
* The AUR repo contains *only* the `PKGBUILD`, `outspline.install` and `.SRCINFO` files, so you need to call `makepkg` from the cloned folder; the whole procedure is explained [here](https://github.com/kynikos/outspline/wiki/Installation-in-Arch-Linux).
* SourceForge contains the "ready-to-install" source, i.e. a *selection* of the files in the GitHub repo, necessary to separate the various "components" (i.e. groups of addons) into the respective packages; this is the product of the *release* procedure I mentioned above, hence it's what the PKGBUILD has to download.

At that stage I suppose you tried to run `setup.py` from the `src` folder, but the `config.py` module doesn't exist there literally, it has to be renamed from one of the `*.config.py` files which exist for each official *component*, and this is still part of the release procedure. This is what was causing `ImportError` for you.

About using submodules, I've never really liked the way they need to be managed, but this is only my personal preference, and I understand it may create problems for those who don't follow the [development environment](https://github.com/kynikos/outspline/wiki/Development-environment) instructions.

For the time being, I've linked this issue from the [Troubleshooting](https://github.com/kynikos/outspline/wiki/Troubleshooting#i-cant-install-outspline) wiki page, and I've put a README into the `src` folder; hopefully this will help others in the future :)

**Comment by xguse** [comment]
First, thanks for your response!  I REALLY liked the description of outspline and was VERY VERY eager to try it out.  

>Is that what you mean with "Because I couldnt get it from the AUR [...]"?

Yes I `yaourt -S`ed it and it said:

```shell
gus at jupiter in ~
$ yaourt -S outspline

==> Downloading outspline PKGBUILD from AUR...
==> ERROR: outspline not found in AUR.
```

*It __still__ says this btw*.

 So from there I tried to cURL the URL that was encoded in the PKGBUILD.  It stalled out so I figured that that was why `yaourt` was failing.  From there I went to the github repo.

As it turns out the SF link DID work it just took a while to to start showing progress on the cURL output for some reason.  


>Anyhow, if I understand correctly, after failing to download the snapshot with curl because of the wiki issue, you tried to clone the GitHub repo, but you weren't aware that the files on GitHub, AUR and SourceForge all have different purposes:

Yes I understand the different purposes __now__.  But as most projects that I have encountered on github use it to both VC *and* distribute the software, it was not evident right away from looking at the `README` which is all that most people will start with as github has made people accustomed to information rich content in these. 

I will send a quick PR for the README that is hopefully in the spirit of both "universal application" across the SF releases and the "culture of information rich READMEs" conventions of github.


>The AUR repo contains only the PKGBUILD, outspline.install and .SRCINFO files, so you need to call makepkg from the cloned folder; the whole procedure is explained here.

Yes, I am quite familiar with this process.  Thank you none-the-less.

>About using submodules, I've never really liked the way they need to be managed, but this is only my personal preference, 

To tell you the truth, __I agree__. They are more than a little annoying.

Anyway I need to get back to work.  Thank you for taking the time to respond and thank you for the software!

**Comment by xguse** [comment]
I also want to confirm that 

1. cloning the PKGBUILD etc from the aur website
2. running `makepkg -si`  from inside the repo dir

works for me.

**Comment by kynikos** [comment]
>It still says this btw.

Um... it's probably a problem with *yaourt*, did you update it after the migration to AUR4? Does it work with other AUR4 packages? I don't use yaourt, but I've tried reinstalling Outspline with *pacaur*, for example, without issues, and as you say, the manual installation procedure works too (thanks for confirming).

>Thank you for taking the time to respond and thank you for the software!

No worries, I'm glad to know it's helpful to somebody else! However as you've noticed I don't consider it at version 1.0 yet, which means it still lacks some features that might be somewhat expected, and has some minor known usage bugs that you'll probably notice while using it. Also, I consider the current version *stable*, as it's never corrupted my database, despite my continuous, everyday usage; however, you are only the second person who's given me some sort of feedback for this program, which means that it's practically not been tested by people who may use it in ways different from those that I designed it for, hence make sure to **regularly** use the **save backup** feature, so as to prevent possible future regrets ;) Finally, I will of course appreciate it if you will keep reporting any new problems that you may discover!

**Comment by kynikos** [comment]
Ah, also I'm glad that you've made it to properly build the package and install it with makepkg/pacman, since calling `setup.py` directly is discouraged, and should only be used to create build instructions like a PKGBUILD or the equivalents for other distros.
