### ISSUE TITLE
0.8.2 install errors with Python 3.5

### ISSUE THREAD

**Issue by fire-eggs** [kynikos/outspline#377]
Trying to follow the "python setup.py install" instructions.

byte-compiling E:\Python35\Lib\site-packages\outspline\static\activestate\tco.py to tco.cpython-35.pyc
  File "E:\Python35\Lib\site-packages\outspline\static\activestate\tco.py", line 37
    except TailRecurseException, err:
                               ^
SyntaxError: invalid syntax

byte-compiling E:\Python35\Lib\site-packages\outspline\coreaux\configuration.py to configuration.cpython-35.pyc
  File "E:\Python35\Lib\site-packages\outspline\coreaux\configuration.py", line 43
    _USER_FOLDER_PERMISSIONS = 0750
                                  ^
SyntaxError: invalid token

**Comment by kynikos** [comment]
Thank you for the report, Outspline requires Python 2 because wxPython doesn't support version 3 yet. You can view all the dependencies in https://github.com/kynikos/outspline/wiki/Dependencies :)

What distro are you using? There should be the possibility to have both versions of Python installed: in order to use Python 2, the command should be `python2` instead of just `python`.

**Comment by kynikos** [comment]
I'm going to close this, as it wasn't a bug.
